<?php

namespace AppBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche des events en cours
     *
     * Author: Delrodie AMOIKON
     * Date: 15/10/2017
     * v1.0
     */
    public function findEvent($offset, $limit)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery('
                    SELECT a, t
                    FROM AppBundle:Agenda a
                    LEFT JOIN a.typevent t
                    WHERE a.datedebut <= :date
                    AND a.datefin >= :date
                    ORDER BY a.datevent ASC
                ')
                ->setFirstResult($offset)
                ->setMaxResults($limit)
                ->setParameter('date', date('Y-m-d', time()));

        return $qb->getResult();
    }
}
