<?php

namespace AppBundle\Repository;

/**
 * PubliciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * REcherche de la publicité seon le type de format
     *
     * Author: Delrodie AMOIKON
     * Date: 17/10/2017 06:33
     * v1.0
     */
    public function findByTypub($type, $offset, $limit)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQuery('
                    SELECT p, t
                    FROM AppBundle:Publicite p
                    LEFT JOIN p.typub t
                    WHERE t.nom LIKE :type
                    AND p.statut = :actif
                    AND p.debutpub <= :date
                    AND p.finpub >= :date
                    ORDER BY p.id DESC
                  ')
                  ->setFirstResult($offset)
                  ->setMaxResults($limit)
                  ->setParameters(array(
                      'type'  => '%'.$type.'%',
                      'actif' => 1,
                      'date'  => date('Y-m-d', time())
                  ))
                  ->getResult();

        return $qb;
    }
}
