<?php

namespace AppBundle\Repository;

/**
 * TypeventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeventRepository extends \Doctrine\ORM\EntityRepository
{
}
