<?php

namespace AppBundle\Repository;

/**
 * TypostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypostRepository extends \Doctrine\ORM\EntityRepository
{
}
