<?php

namespace AppBundle\Repository;

/**
 * TypubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypubRepository extends \Doctrine\ORM\EntityRepository
{
}
